### ISSUE TITLE
Having some issues building on macOS Catalina/Big Sur

### ISSUE THREAD

**Issue by stochastic-thread** [hoytech/quadrable#2]
Can't seem to find any docs on building liblmdb-dev for macOS. Any ideas?

```c++ quadb.o -flto  -l:liblmdb.a -pthread -o quadb
ld: library not found for -l:liblmdb.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [quadb] Error 1
```

This seems like a cool project, I'd love to give it a spin

**Comment by hoytech** [comment]
Hi! Thanks for giving it a try. I've never tested it on Mac OS, but I'm pretty sure it should work.

Since you got to the linking stage I expect lmdb is installed (for anyone else reading in the future, I think you can get lmdb through `brew install lmdb`).

Can you please try editing `Makefile` and changing the `LDLIBS` line? Change `-l:liblmdb.a` to `-llmdb` and the run `make` again.

Thank you!

**Comment by stochastic-thread** [comment]
yup that worked. thanks 👍

Happy to close out this issue but I'm curious what your use case was for this? I like the idea of a Redis-esque API with the ability to backup a small amount of data that describes the entire data set, might have useful applications in decentralized data storage. Do you have a tweeter?

**Comment by hoytech** [comment]
Glad to hear it worked! I pushed this change to the repo so now this will be the default. I had it linked statically so I could just copy the quadb binary over to another machine more easily, but dynamic linking is probably better here.

The main use-case for Quadrable that I had in mind was for an optimistic roll-up system, but I tried to make it as general purpose as possible. You would need to build a special redis-like adaptor on top of Quadrable since it works at a lower level than this, although I agree that is a cool idea.

Nope, no twitter sorry. But you can always reach me through email or github.

Thanks for your bug report!
